
name:                vc-gen
version:             0.1.0.0
github:              "githubuser/vc-gen"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/vc-gen#readme>

dependencies:
- base >= 4.7 && < 5
- z3
- containers
- composition
- mtl
- transformers
- language-ecmascript
- parsec
- cmdargs

default-extensions:
- ConstraintKinds
- DeriveAnyClass
- DeriveDataTypeable
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- PatternSynonyms
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
  - src

executables:
  vc-gen-exe:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vc-gen

tests:
  vc-gen-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vc-gen
    - hspec
    - hspec-core
    - HUnit
    - hrubric
    - ansi-terminal
    - emit-grade
    - directory
